name: testa core

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test_db

        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Realizar o checkout
        uses: actions/checkout@v2

      - name: Instala o python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: insatala pkgs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run migrations
        run: |
          python core/manage.py makemigrations
          python core/manage.py migrate
      - name: run tests
        run: |
          cd core
          pytest --cov
